Presentation.Web/Models/Project/ConstructionProgramViewModel.cs
#region Head
// <copyright file="ConstructionProgramViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.ComponentModel;

namespace Presentation.Web.Models.Project
{
    public class ConstructionProgramViewModel
    {
        public int Id { get; set; }
        [DisplayName("År med projekt involveret")]
        public int YearOfProjectInvolvement { get; set; }
    }
}

Presentation.Web/Models/Project/CreateProjectViewModel.cs
#region Head
// <copyright file="CreateProjectViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Spatial;
using Presentation.Web.Filters;
using Presentation.Web.Models.Shared;
using Presentation.Web.Validators;

namespace Presentation.Web.Models.Project
{
    public class CreateProjectViewModel :   LoggerViewModel,
                                            ISelectedAdvisor,
                                            ISelectedConstructionProgram,
                                            ISelectedCouncil,
                                            ISelectedGroup,
                                            ISelectedLocalCommunity,
                                            ISelectedProjectCategory,
                                            ISelectedProjectLeader
    {
        public CreateProjectViewModel()
        {
            Documents = new List<ProjectDocumentViewModel>();
            SearchInAarhus = true;
            StreetType = StreetTypeViewModel.PublicStreet;
            ExpectedStartDate = DateTime.Now;
            ExpectedEndDate = DateTime.Now;

            OneYearReview = DateTime.Now;
            OneYearReview.AddYears(1);
            FiveYearReview = DateTime.Now;
            FiveYearReview.AddYears(5);
        }

        public int Id { get; set; }

        [Display(Name = "Emne*")]
        [Required(ErrorMessage = "Angiv venligst projektets emne.")]
        public string Topic { get; set; }

        [UIHint ("Date")]
        [Display(Name = "Forventet startdato*")]
        [Required(ErrorMessage = "Angiv venligst projektets startstidspunkt.")]
        public DateTime ExpectedStartDate { get; set; }

        [UIHint("Date")]
        [Display(Name = "Forventet slutdato*")]
        [Required(ErrorMessage = "Angiv venligst projektets slutstidspunkt.")]
        public DateTime ExpectedEndDate { get; set; }

        [Display(Name = "Beskrivelse")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Note")]
        [DataType(DataType.MultilineText)]
        public string Note { get; set; }

        [Display(Name = "Vejtype")]
        public StreetTypeViewModel StreetType { get; set; }

        [Display(Name = "Projektleder")]
        public int? ProjectLeaderId { get; set; }

        [Display(Name = "Rådsprioritet*")]
        [Required(ErrorMessage = "Angiv venligst projektets rådsprioritet.")]
        [Range(1, 10, ErrorMessage = "Prioriteten skal være mellem 1 og 10.")]
        public int CouncilPriority { get; set; }

        [Display(Name = "Kommuneprioritet*")]
        [Required(ErrorMessage = "Angiv venligst projektets kommuneprioritet.")]
        [Range(1, 10, ErrorMessage = "Prioriteten skal være mellem 1 og 10.")]
        public int MunicipalityPriority { get; set; }

        [Display(Name = "Adresse")]
        public Guid AddressId { get; set; }

        public DbGeometry AddressLocation { get; set; }

        [Display(Name = "Foreløbig adresse?")]
        public bool TemporaryAddress { get; set; }

        [Display(Name = "Søg i Aarhus?")]
        public bool SearchInAarhus { get; set; }

        [Display(Name = "Budget*")]
        [Required(ErrorMessage = "Angiv venligst projektets budget.")]
        [ThousandsNumber(ErrorMessage = "Brug punktum som seperator. Min/max værdi er 2.147.483.647")]
        public string Budget { get; set; }

        [Display(Name = "Status")]
        public ProjectStatusTypeViewModel ProjectStatus { get; set; }

        [Display(Name = "Rådgiver")]
        public int? AdvisorId { get; set; }

        [Display(Name = "Projektkategori")]
        public int? ProjectCategoryId { get; set; }

        [Display(Name = "Gruppe")]
        public int? GroupId { get; set; }

        [Display(Name = "Anlægsprogram")]
        public int? ConstructionProgramId { get; set; }

        [Display(Name = "Lokalsamfund")]
        public int? LocalCommunityId { get; set; }

        [Display(Name = "Fællesråd")]
        public int? CouncilId { get; set; }

        [UIHint("Date")]
        [Display(Name = "1 års gennemgang")]
        public DateTime OneYearReview { get; set; }

        [UIHint("Date")]
        [Display(Name = "5 års gennemgang")]
        public DateTime FiveYearReview { get; set; }

        public IList<ProjectDocumentViewModel> Documents { get; set; }
    }
}

Presentation.Web/Models/Project/ProjectDocumentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Presentation.Web.Models.Project
{
    public class ProjectDocumentViewModel
    {
        public Guid Guid { get; set; }
        public string FileName { get; set; }
        public float FileSize { get; set; }

        [DataType (DataType.MultilineText)]
        public string Comment { get; set; }
        public int? ProjectId { get; set; }
    }
}

Presentation.Web/Models/Project/ProjectDto.cs
#region Head
// <copyright file="CreateAgendaPointProjectDto.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.Diagnostics.CodeAnalysis;

namespace Presentation.Web.Models.Project
{
    [SuppressMessage("Microsoft.Naming", "CA1704", Justification = "Dto is a valid abbreviation.")]
    public class ProjectDto
    {
        public int Id { get; set; }
        public string Name{ get; set; }
    }
}

Presentation.Web/Controllers/ProjectController.cs
#region Head
// <copyright file="ProjectController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Core.DomainModel;
using Core.DomainServices;
using Presentation.Web.Filters;
using Presentation.Web.Helpers;
using Presentation.Web.Models;
using Presentation.Web.Models.Project;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Controllers
{
    public class ProjectController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IGenericRepository<Project> _projectRepository;
        private readonly IMappingEngine _mapper;
        private readonly IGenericRepository<ProjectDocument> _documentRepository;
        private readonly IDocumentHelper _documentHelper;
        private readonly IDateTime _dateTime;
        private readonly IGeoCoder _geoCoder;
        private readonly IDawaRepository _dawaRepo;

        public ProjectController(IUnitOfWork unitOfWork,
            IGenericRepository<Project> projectRepository,
            IMappingEngine mapper,
            IGenericRepository<ProjectDocument> documentRepository,
            IDocumentHelper documentHelper,
            IDateTime dateTime,
            IGeoCoder geoCoder,
            IDawaRepository dawaRepo)
        {
            _unitOfWork = unitOfWork;
            _projectRepository = projectRepository;
            _mapper = mapper;
            _documentRepository = documentRepository;
            _documentHelper = documentHelper;
            _dateTime = dateTime;
            _geoCoder = geoCoder;
            _dawaRepo = dawaRepo;
        }

        // GET: Project
        public ActionResult Index(bool onlyAwaitingProjects = true)
        {
            var projects = _projectRepository.Get();

            if (onlyAwaitingProjects)
                projects = projects.Where(p => p.ProjectStatus == ProjectStatusType.Awaiting);

            var vms = _mapper.Map<IEnumerable<IndexProjectViewModel>>(projects);

            ViewBag.onlyAwaitingProjects = onlyAwaitingProjects;

            return View(vms);
        }

        // GET: Project/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = _projectRepository.GetByKey(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<IndexProjectViewModel>(project);

            return View(vm);
        }

        // GET: Project/Create
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Create()
        {
            var vm = new CreateProjectViewModel();
            return View(vm);
        }

        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Create(CreateProjectViewModel createProjectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(createProjectViewModel);
            }

            var project = _mapper.Map<Project>(createProjectViewModel);

            if (project.Documents != null)
            {
                var guidList = project.Documents.Select(o => o.Guid).ToList();
                project.Documents.Clear();

                // foreach guid in vm, get document from db and insert in created project
                foreach (var guid in guidList)
                {
                    var guid1 = guid;
                    var document = _documentRepository.Get(o => o.Guid == guid1).First();
                    project.Documents.Add(document);
                }
            }
            project.CreatedBy = AdHelper.Name;
            project.CreatedOn = _dateTime.Now;

            // add spartialobject
            project.AddressLocation = _geoCoder.GetSpartialObject(project.AddressId);

            // Fetch address details from server and save to local DB
            var addr = _dawaRepo.GetAddress(createProjectViewModel.AddressId);
            project.AddressStreetName = addr.StreetName;
            project.AddressNumber = addr.Number;

            _projectRepository.Insert(project);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Project/Edit/5
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var project = _projectRepository.GetByKey(id);
            if (project == null) return HttpNotFound();

            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<CreateProjectViewModel>(project);

            return View(vm);
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Edit(CreateProjectViewModel createProjectViewModel)
        {
            var project = _projectRepository.GetByKey(createProjectViewModel.Id);

            if (!ModelState.IsValid)
            {
                SetCreatedModifiedInViewBag(project);
                return View(createProjectViewModel);
            }

            if (createProjectViewModel.Documents != null && createProjectViewModel.Documents.Any())
            {
                var originalGuidsList = project.Documents.Select(o => o.Guid).ToList();
                var guidsList = createProjectViewModel.Documents.Select(o => o.Guid).ToList();

                // get guids for document(s) to remove
                var exceptGuids = originalGuidsList.Except(guidsList).ToList();

                // Delete removed documents
                foreach (var exceptGuid in exceptGuids)
                {
                    _documentRepository.DeleteByKey(exceptGuid);
                    DeleteFilesFromServer(exceptGuids.ToList());
                }

            }

            // Geocoding
            if (createProjectViewModel.AddressId != project.AddressId)
                createProjectViewModel.AddressLocation = _geoCoder.GetSpartialObject(createProjectViewModel.AddressId);

            _mapper.Map(createProjectViewModel, project);

            if (project.Documents != null)
            {
                var documentList = project.Documents.ToList();
                project.Documents.Clear();

                // foreach guid in vm, get document from db and insert in project
                foreach (var doc in documentList)
                {
                    var guid1 = doc.Guid;
                    var document = _documentRepository.Get(o => o.Guid == guid1).First();
                    document.ProjectId = project.Id;
                    document.Comment = doc.Comment;

                    // update document through documentRepository, because EF marks navigation properties of parent as unmodified
                    _documentRepository.Update(document);

                    project.Documents.Add(document);
                }
            }

            project.ModifiedBy = AdHelper.Name;
            project.ModifiedOn = _dateTime.Now;

            // Fetch address details from server and save to local DB
            var addr = _dawaRepo.GetAddress(createProjectViewModel.AddressId);
            project.AddressStreetName = addr.StreetName;
            project.AddressNumber = addr.Number;

            _projectRepository.Update(project);
            _unitOfWork.Save();
            return RedirectToAction("Details", new { id = project.Id });
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var project = _projectRepository.GetByKey(id);
            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<IndexProjectViewModel>(project);

            return View(vm);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var documents = _documentRepository.Get(o => o.ProjectId == id).ToList();
            // delete all attached documents from server
            DeleteFilesFromServer(documents.Select(o => o.Guid));

            // delete doc from db
            foreach (var doc in documents)
            {
                _documentRepository.DeleteByKey(doc.Guid);
            }

            _projectRepository.DeleteByKey(id);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        /// <summary>

Presentation.Web/Views/Project/Delete.cshtml
@model Presentation.Web.Models.Project.IndexProjectViewModel
@{
    ViewBag.Title = "Slet";
}

<h2>Slet</h2>

@Html.Partial("CreatedModifiedPartialView")
<hr class="hidden-xs" />

<h3>Er du sikker på at du vil slette projektet?</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.Topic)</dt>
                <dd>@Html.DisplayFor(model => model.Topic)</dd>

                <dt>@Html.DisplayNameFor(model => model.ExpectedStartDate)</dt>
                <dd>@Html.DisplayFor(model => model.ExpectedStartDate)</dd>

                <dt>@Html.DisplayNameFor(model => model.ExpectedEndDate)</dt>
                <dd>@Html.DisplayFor(model => model.ExpectedEndDate)</dd>

                <dt>@Html.DisplayNameFor(model => model.Description)</dt>
                <dd>@Html.DisplayFor(model => model.Description)</dd>

                <dt>@Html.DisplayNameFor(model => model.Note)</dt>
                <dd>@Html.DisplayFor(model => model.Note)</dd>

                <dt>@Html.DisplayNameFor(model => model.StreetType)</dt>
                <dd>@Html.DisplayFor(model => model.StreetType)</dd>

                <dt>@Html.DisplayNameFor(model => model.ProjectLeader.Name)</dt>
                <dd>@Html.DisplayFor(model => model.ProjectLeader.Name)</dd>

                <dt>@Html.DisplayNameFor(model => model.CouncilPriority)</dt>
                <dd>@Html.DisplayFor(model => model.CouncilPriority)</dd>

                <dt>@Html.DisplayNameFor(model => model.MunicipalityPriority)</dt>
                <dd>@Html.DisplayFor(model => model.MunicipalityPriority)</dd>

                <dt>@Html.DisplayNameFor(model => model.AddressId)</dt>
                <dd class="aws-address-id" data-aws-id="@Model.AddressId">Henter addresse...</dd>

                <dt>@Html.DisplayNameFor(model => model.TemporaryAddress)</dt>
                <dd>@Html.DisplayFor(model => model.TemporaryAddress)</dd>

                <dt>@Html.DisplayNameFor(model => model.Budget)</dt>
                <dd>@Html.DisplayFor(model => model.Budget)</dd>

                <dt>@Html.DisplayNameFor(model => model.ProjectStatus)</dt>
                <dd>@Html.DisplayFor(model => model.ProjectStatus)</dd>
            </dl>
        </div>

        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Advisor)
                </dt>

                <dd>
                    @if (Model.Advisor != null)
                    {
                        <b>Virksomhed: </b>
                        @Html.DisplayFor(model => model.Advisor.CompanyName)
                        <br />
                        <b>Ansvarlig person: </b>
                        @Html.DisplayFor(model => model.Advisor.ResponsiblePersonName)
                        <br />
                        <b>Telefonnummer: </b>
                        @Html.DisplayFor(model => model.Advisor.ResponsiblePersonPhoneNumber)
                    }
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ProjectCategory)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ProjectCategory.Category)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Group)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Group.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ConstructionProgram)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ConstructionProgram.YearOfProjectInvolvement)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LocalCommunity.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LocalCommunity.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Documents)
                </dt>
                @foreach (var doc in Model.Documents)
                {
                    <dd>
                        <a href="@Url.Action("Download", "Project", new { guid = doc.Guid })">@doc.FileName</a>
                    </dd>
                    <dd class="bg-info">
                        @Html.DisplayFor(model => doc.Comment)
                    </dd>
                    <br />
                }
            </dl>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row">
            <div class="col-md-12">
                <input type="submit" value="Slet" class="btn btn-danger" /> | @Html.ActionLink("Gå tilbage", "Index") | @Html.ActionLink("Rediger", "Edit", new { id = Model.Id })
            </div>
        </div>
    }
</div>

Presentation.Web/Views/Project/Details.cshtml
@model Presentation.Web.Models.Project.IndexProjectViewModel
@{
    ViewBag.Title = "Detaljer";
}

<h2>Projekt</h2>

@Html.Partial("CreatedModifiedPartialView")
<hr class="hidden-xs" />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.Id)</dt>
                <dd>@Html.DisplayFor(model => model.Id)</dd>

                <dt>@Html.DisplayNameFor(model => model.AddressId)</dt>
                <dd class="aws-address-id" data-aws-id="@Model.AddressId">Henter adresse...</dd>

                <dt>@Html.DisplayNameFor(model => model.TemporaryAddress)</dt>
                <dd>@Html.DisplayFor(model => model.TemporaryAddress)</dd>

                <dt>@Html.DisplayNameFor(model => model.Topic)</dt>
                <dd>@Html.DisplayFor(model => model.Topic)</dd>

                <dt>@Html.DisplayNameFor(model => model.ExpectedStartDate)</dt>
                <dd>@Html.DisplayFor(model => model.ExpectedStartDate)</dd>

                <dt>@Html.DisplayNameFor(model => model.ExpectedEndDate)</dt>
                <dd>@Html.DisplayFor(model => model.ExpectedEndDate)</dd>

                @if (!string.IsNullOrEmpty(Model.Description))
                {
                    <dt>@Html.DisplayNameFor(model => model.Description)</dt>
                    <dd class="description-details">@Html.DisplayFor(model => model.Description)</dd>
                }

                @if (!string.IsNullOrEmpty(Model.Note))
                {
                    <dt>@Html.DisplayNameFor(model => model.Note)</dt>
                    <dd class="note-details">@Html.DisplayFor(model => model.Note)</dd>
                }

                <dt>@Html.DisplayNameFor(model => model.StreetType)</dt>
                <dd>@Html.DisplayFor(model => model.StreetType)</dd>

                <dt>@Html.DisplayNameFor(model => model.ProjectLeader)</dt>
                <dd>
                    @if (Model.ProjectLeader != null)
                    {
                        <b>Navn: </b>
                        @Html.DisplayFor(model => model.ProjectLeader.Name)
                        <br />
                        <b>Initialer: </b>
                        @Html.DisplayFor(model => model.ProjectLeader.Initials)
                        <br />
                        <b>Aktiv: </b>
                        @Html.DisplayFor(model => model.ProjectLeader.IsActive)
                    }
                </dd>

                <dt>@Html.DisplayNameFor(model => model.CouncilPriority)</dt>
                <dd>@Html.DisplayFor(model => model.CouncilPriority)</dd>

                <dt>@Html.DisplayNameFor(model => model.MunicipalityPriority)</dt>
                <dd>@Html.DisplayFor(model => model.MunicipalityPriority)</dd>

                <dt>@Html.DisplayNameFor(model => model.Budget)</dt>
                <dd>@Html.DisplayFor(model => model.Budget)</dd>

                <dt>@Html.DisplayNameFor(model => model.ProjectStatus)</dt>
                <dd>@Html.DisplayFor(model => model.ProjectStatus)</dd>

                <dt>@Html.DisplayNameFor(model => model.OneYearReview)</dt>
                <dd>@Html.DisplayFor(model => model.OneYearReview)</dd>

                <dt>@Html.DisplayNameFor(model => model.FiveYearReview)</dt>
                <dd>@Html.DisplayFor(model => model.FiveYearReview)</dd>
            </dl>
        </div>
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.Advisor)</dt>
                <dd>
                    @if (Model.Advisor != null)
                    {
                        <b>Virksomhed: </b>
                        @Html.DisplayFor(model => model.Advisor.Company.Name)
                        <br />
                        <b>Ansvarlig person: </b>
                        @Html.DisplayFor(model => model.Advisor.ResponsiblePersonName)
                        <br />
                        <b>Telefonnummer: </b>
                        @Html.DisplayFor(model => model.Advisor.ResponsiblePersonPhoneNumber)
                    }
                </dd>

                <dt>@Html.DisplayNameFor(model => model.ProjectCategory)</dt>
                <dd>@Html.DisplayFor(model => model.ProjectCategory.Category)</dd>

                <dt>@Html.DisplayNameFor(model => model.Group)</dt>
                <dd>@Html.DisplayFor(model => model.Group.Name)</dd>

                <dt>@Html.DisplayNameFor(model => model.ConstructionProgram)</dt>
                <dd>@Html.DisplayFor(model => model.ConstructionProgram.YearOfProjectInvolvement)</dd>

                <dt>@Html.DisplayNameFor(model => model.LocalCommunity.Name)</dt>
                <dd>@Html.DisplayFor(model => model.LocalCommunity.Name)</dd>

                <dt>@Html.DisplayNameFor(model => model.Council)</dt>
                <dd>@Html.DisplayFor(model => model.Council.Name)</dd>

                <dt>@Html.DisplayNameFor(model => model.Documents)</dt>
                @foreach (var doc in Model.Documents)
                {
                    <dd>
                        <a href="@Url.Action("Download", "Project" , new { guid=doc.Guid })">@doc.FileName</a>
                    </dd>
                    <dd class="bg-info">
                        @Html.DisplayFor(model => doc.Comment)
                    </dd>
                    <br />
                }
            </dl>
        </div>
    </div>

    <p>
        @Html.ActionLink("Rediger", "Edit", new { id = Model.Id }) | @Html.ActionLink("Tilbage til liste", "Index")
        | <a data-aws-id="@Model.AddressId" class="map-link" target="_blank" href=""><span class="glyphicon glyphicon-map-marker"></span> Vis på kort</a>
    </p>
</div>