Presentation.Web/Models/Search/AgendaPointViewModel.cs
#region Head
// <copyright file="AgendaPointViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Presentation.Web.Models.Shared;
namespace Presentation.Web.Models.Search
{
    public class AgendaPointViewModel : LoggerViewModel
    {
        public int Id { get; set; }

        [DisplayName("Repræsentativ adresse")]
        public Guid AddressId { get; set; }

        [DisplayName("Ansvarlig")]
        public string ResponsiblePersonName { get; set; }

        [DisplayName("Vejtype")]
        public StreetTypeViewModel StreetType { get; set; }

        [DisplayName("Emne")]
        public string TopicName { get; set; }

        [DisplayName("Beskrivelse")]
        public string Description { get; set; }

        [DisplayName("Afgørelse")]
        [DataType(DataType.MultilineText)]
        public string Conclusion { get; set; }

        [DisplayName("Aftale")]
        [DataType(DataType.MultilineText)]
        public string Agreement { get; set; }

        [DisplayName("Status")]
        public AgendaPointStatusTypeViewModel Status { get; set; }

        public int? ProjectId { get; set; }

        [DisplayName("Projektemne")]
        public string ProjectTopic { get; set; }

        [DisplayName("Tidligere møder")]
        public IEnumerable<string> MeetingIds { get; set; }

        /// <summary>
        /// Determing wheter the point can be deleted by the current user
        /// </summary>
        [DisplayName("Kan slettes?")]
        public bool IsDeleableForCurrentUser { get; set; }
    }
}

Presentation.Web/Models/Search/ResultsViewModel.cs
#region Head
// <copyright file="ResultsSearchViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace Presentation.Web.Models.Search
{
    public class ResultsViewModel
    {
        public ResultsViewModel()
        {
            Projects = new List<ProjectViewModel>();
            AgendaPoints = new List<AgendaPointViewModel>();
        }

        [DisplayName("Projekter")]
        public IEnumerable<ProjectViewModel> Projects { get; set; }

        [DisplayName("Færdselsmødepunkter")]
        public IEnumerable<AgendaPointViewModel> AgendaPoints { get; set; }

        /// <summary>
        /// Get summed count of project and agenda point lists.
        /// </summary>
        /// <returns>Summed count of lists</returns>
        public int Count()
        {
            return Projects.Count() + AgendaPoints.Count();
        }
    }
}

Presentation.Web/Controllers/ProjectController.cs
#region Head
// <copyright file="ProjectController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Core.DomainModel;
using Core.DomainServices;
using Presentation.Web.Filters;
using Presentation.Web.Helpers;
using Presentation.Web.Models;
using Presentation.Web.Models.Project;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Controllers
{
    public class ProjectController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IGenericRepository<Project> _projectRepository;
        private readonly IMappingEngine _mapper;
        private readonly IGenericRepository<ProjectDocument> _documentRepository;
        private readonly IDocumentHelper _documentHelper;
        private readonly IDateTime _dateTime;
        private readonly IGeoCoder _geoCoder;
        private readonly IDawaRepository _dawaRepo;

        public ProjectController(IUnitOfWork unitOfWork,
            IGenericRepository<Project> projectRepository,
            IMappingEngine mapper,
            IGenericRepository<ProjectDocument> documentRepository,
            IDocumentHelper documentHelper,
            IDateTime dateTime,
            IGeoCoder geoCoder,
            IDawaRepository dawaRepo)
        {
            _unitOfWork = unitOfWork;
            _projectRepository = projectRepository;
            _mapper = mapper;
            _documentRepository = documentRepository;
            _documentHelper = documentHelper;
            _dateTime = dateTime;
            _geoCoder = geoCoder;
            _dawaRepo = dawaRepo;
        }

        // GET: Project
        public ActionResult Index(bool onlyAwaitingProjects = true)
        {
            var projects = _projectRepository.Get();

            if (onlyAwaitingProjects)
                projects = projects.Where(p => p.ProjectStatus == ProjectStatusType.Awaiting);

            var vms = _mapper.Map<IEnumerable<IndexProjectViewModel>>(projects);

            ViewBag.onlyAwaitingProjects = onlyAwaitingProjects;

            return View(vms);
        }

        // GET: Project/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = _projectRepository.GetByKey(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<IndexProjectViewModel>(project);

            return View(vm);
        }

        // GET: Project/Create
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Create()
        {
            var vm = new CreateProjectViewModel();
            return View(vm);
        }

        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Create(CreateProjectViewModel createProjectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(createProjectViewModel);
            }

            var project = _mapper.Map<Project>(createProjectViewModel);

            if (project.Documents != null)
            {
                var guidList = project.Documents.Select(o => o.Guid).ToList();
                project.Documents.Clear();

                // foreach guid in vm, get document from db and insert in created project
                foreach (var guid in guidList)
                {
                    var guid1 = guid;
                    var document = _documentRepository.Get(o => o.Guid == guid1).First();
                    project.Documents.Add(document);
                }
            }
            project.CreatedBy = AdHelper.Name;
            project.CreatedOn = _dateTime.Now;

            // add spartialobject
            project.AddressLocation = _geoCoder.GetSpartialObject(project.AddressId);

            // Fetch address details from server and save to local DB
            var addr = _dawaRepo.GetAddress(createProjectViewModel.AddressId);
            project.AddressStreetName = addr.StreetName;
            project.AddressNumber = addr.Number;

            _projectRepository.Insert(project);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Project/Edit/5
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var project = _projectRepository.GetByKey(id);
            if (project == null) return HttpNotFound();

            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<CreateProjectViewModel>(project);

            return View(vm);
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        public ActionResult Edit(CreateProjectViewModel createProjectViewModel)
        {
            var project = _projectRepository.GetByKey(createProjectViewModel.Id);

            if (!ModelState.IsValid)
            {
                SetCreatedModifiedInViewBag(project);
                return View(createProjectViewModel);
            }

            if (createProjectViewModel.Documents != null && createProjectViewModel.Documents.Any())
            {
                var originalGuidsList = project.Documents.Select(o => o.Guid).ToList();
                var guidsList = createProjectViewModel.Documents.Select(o => o.Guid).ToList();

                // get guids for document(s) to remove
                var exceptGuids = originalGuidsList.Except(guidsList).ToList();

                // Delete removed documents
                foreach (var exceptGuid in exceptGuids)
                {
                    _documentRepository.DeleteByKey(exceptGuid);
                    DeleteFilesFromServer(exceptGuids.ToList());
                }

            }

            // Geocoding
            if (createProjectViewModel.AddressId != project.AddressId)
                createProjectViewModel.AddressLocation = _geoCoder.GetSpartialObject(createProjectViewModel.AddressId);

            _mapper.Map(createProjectViewModel, project);

            if (project.Documents != null)
            {
                var documentList = project.Documents.ToList();
                project.Documents.Clear();

                // foreach guid in vm, get document from db and insert in project
                foreach (var doc in documentList)
                {
                    var guid1 = doc.Guid;
                    var document = _documentRepository.Get(o => o.Guid == guid1).First();
                    document.ProjectId = project.Id;
                    document.Comment = doc.Comment;

                    // update document through documentRepository, because EF marks navigation properties of parent as unmodified
                    _documentRepository.Update(document);

                    project.Documents.Add(document);
                }
            }

            project.ModifiedBy = AdHelper.Name;
            project.ModifiedOn = _dateTime.Now;

            // Fetch address details from server and save to local DB
            var addr = _dawaRepo.GetAddress(createProjectViewModel.AddressId);
            project.AddressStreetName = addr.StreetName;
            project.AddressNumber = addr.Number;

            _projectRepository.Update(project);
            _unitOfWork.Save();
            return RedirectToAction("Details", new { id = project.Id });
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var project = _projectRepository.GetByKey(id);
            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<IndexProjectViewModel>(project);

            return View(vm);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var documents = _documentRepository.Get(o => o.ProjectId == id).ToList();
            // delete all attached documents from server
            DeleteFilesFromServer(documents.Select(o => o.Guid));

            // delete doc from db
            foreach (var doc in documents)
            {
                _documentRepository.DeleteByKey(doc.Guid);
            }

            _projectRepository.DeleteByKey(id);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        /// <summary>

Presentation.Web/Controllers/SearchController.cs
#region Head
// <copyright file="SearchController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Core.ApplicationServices;
using Core.DomainModel;
using Core.DomainServices;
using Presentation.Web.Filters;
using Presentation.Web.Models.Search;

namespace Presentation.Web.Controllers
{
    public class SearchController : BaseController
    {
        private readonly IMappingEngine  _mapper;
        private readonly ISearchService _searchService;
        private readonly IGenericRepository<Project> _projectRepository;


        public SearchController(IMappingEngine mapper, ISearchService searchService, IGenericRepository<Project> projectRepository)
        {
            _mapper = mapper;
            _searchService = searchService;
            _projectRepository = projectRepository;
        }

        // GET: Search
        [PopulateTopics]
        [PopulateCouncilsRaw]
        [PopulateGroups]
        public ActionResult Index(SearchViewModel viewModel)
        {
            if (viewModel == null)
            {
                viewModel = new SearchViewModel();
            }

            return View(viewModel);
        }

        // POST: Search
        [HttpPost, ActionName("Index")]
        [PopulateTopics]
        [PopulateCouncilsRaw]
        [PopulateGroups]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> IndexPost(SearchViewModel viewModel)
        {
            if (viewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (!viewModel.AnyParametersSet())
            {
                ViewBag.NoSearchParameters = true;
                return View(viewModel);
            }

            var results = new ResultsViewModel();

            try
            {
                if (viewModel.SearchInProjects && viewModel.TopicId == null)
                {
                    var searchParameters = _mapper.Map<ProjectSearchParameters>(viewModel);
                    var projects = await _searchService.GetProjectsAsync(searchParameters);
                    if (projects != null)
                        results.Projects = _mapper.Map<IEnumerable<ProjectViewModel>>(projects);
                }

                if (viewModel.SearchInAgendaPoints && viewModel.CouncilId == null && viewModel.GroupId == null)
                {
                    var searchParameters = _mapper.Map<AgendaPointSearchParameters>(viewModel);
                    var agendaPoints = await _searchService.GetAgendaPointsAsync(searchParameters);
                    if (agendaPoints != null)
                        results.AgendaPoints = _mapper.Map<IEnumerable<AgendaPointViewModel>>(agendaPoints);
                }
            }
            catch (TaskCanceledException)
            {
                ViewBag.TimeOut = true;
                return View("Index", viewModel);
            }

            return View("Results", results);
        }

        public ActionResult PrintSearchResults(IEnumerable<string> projectIds)
        {
            var searchedProjects = projectIds.Select(projectId => _projectRepository.GetByKey(int.Parse(projectId, CultureInfo.InvariantCulture))).ToList();
            var vms = _mapper.Map<IEnumerable<ProjectViewModel>>(searchedProjects);

            return View(vms);
        }
    }
}

Presentation.Web/Views/Search/Index.cshtml
@model Presentation.Web.Models.Search.SearchViewModel
@{
    ViewBag.Title = "Søg";
}

<h2>Søg</h2>
<hr class="hidden-xs" />

@if (ViewBag.NoSearchParameters == true)
{
    <p class="text-danger">Indtast minimum ét søgekriterie og afkryds minimum én boks.</p>
}

@using (Html.BeginForm("Index", "Search", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Address, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @{
                    var selectedAddress = new List<SelectListItem> {new SelectListItem()}; // Empty item to enable dropdown clearing with select2
                    if (Model != null)
                    {
                        selectedAddress.Add(new SelectListItem {Value = Model.Address, Selected = true});
                    }
                }
                @Html.DropDownListFor(model => model.Address, selectedAddress, new {@class = "form-control", id = "address-search", style = "width: 100%", data_only_road_names = "1"})
                @Html.ValidationMessageFor(model => model.Address, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectStatus, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.EnumDropDownListFor(model => model.ProjectStatus, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ProjectStatus, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgendaPointStatus, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.EnumDropDownListFor(model => model.AgendaPointStatus, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.AgendaPointStatus, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.TopicId, ViewBag.TopicList as List<SelectListItem>, "", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.TopicId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.EditorFor(model => model.ProjectId, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ProjectId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.EditorFor(model => model.MeetingId, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.MeetingId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CouncilId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                <select name="@Html.NameFor(model => model.CouncilId)" id="CouncilSelect" class="form-control">
                    <option value=""></option>
                    @foreach (var council in ViewBag.Councils)
                    {
                        <option value="@council.Id" data-group-id="@council.GroupId">@council.Name</option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.CouncilId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.GroupId, ViewBag.GroupList as List<SelectListItem>, "", new {@class = "form-control", @id = "GroupSelect"})
                @Html.ValidationMessageFor(model => model.GroupId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-sm-3"})
            <div class="col-sm-4">
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control", placeholder = "Fra"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
            <div class="col-sm-4 col-sm-offset-1">
                @Html.EditorFor(model => model.EndDate, new {htmlAttributes = new {@class = "form-control", placeholder = "Til"}})
                @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SearchInAgendaPoints, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.CheckBoxFor(model => model.SearchInAgendaPoints, new {@class = "checkbox"})
                @Html.ValidationMessageFor(model => model.SearchInAgendaPoints, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SearchInProjects, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.CheckBoxFor(model => model.SearchInProjects, new {@class = "checkbox"})
                @Html.ValidationMessageFor(model => model.SearchInProjects, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2 col-xs-4 col-sm-offset-3">
                <input type="submit" value="Søg" class="form-control btn btn-success"/>
            </div>
            <div class="col-sm-7 col-xs-8">
                <input type="reset" value="Nulstil" class="btn btn-danger"/>
            </div>
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">
        $(function() {
            var groupSelect = $('#GroupSelect');
            var councilSelect = $('#CouncilSelect');
            var allOptions = new Array();

            councilSelect.find('option').each(function () {
                if ($(this).val() !== '') {
                    allOptions.push({
                        value: $(this).val(),
                        text: $(this).text(),
                        groupId: $(this).attr('data-group-id'),
                    });
                }
            });

            var filterCouncils = function() {
                var selectedGroup = groupSelect.val();

                councilSelect.empty();
                $('<option></option>').appendTo(councilSelect);

                $(allOptions).each(function(i, option) {
                    var councilGroup = $(this).attr('data-group-id');

                    if (selectedGroup === '' || selectedGroup === option.groupId)
                        $('<option></option>').val(option.value).text(option.text).appendTo(councilSelect);
                });
            };

            groupSelect.on('change', filterCouncils);
            filterCouncils();
        });
    </script>
}

Presentation.Web/Views/Search/PrintSearchResults.cshtml
@using Presentation.Web.Models.Search
@model System.Collections.Generic.IEnumerable<Presentation.Web.Models.Search.ProjectViewModel>

@{
    ViewBag.Title = "Fremsøgte projekter";
}

<h2 class="page-header">Fremsøgte projekter</h2>

<button class="hidden-print btn btn-primary pull-right" onclick="printPage()">
    <span class="glyphicon glyphicon-print"></span>
    <span> Print projekter</span>
</button>

@{
    var modelGroupedByGroup = Model.GroupBy(o => o.Group).ToList();
    var ungroupedProjects = new List<ProjectViewModel>();
}

@for (int i = 0; i < modelGroupedByGroup.Count(); i++)
{
    if (modelGroupedByGroup.ElementAt(i).Key == null) // if no group add to ungrouped
    {
        var groupedProject = modelGroupedByGroup.ElementAt(i);

        foreach (var id in groupedProject.Select(o => o.Id).ToList()) // add all ungrouped projects
        {
            var p = Model.Single(o => o.Id == id);
            ungroupedProjects.Add(p);
        }
        continue;
    }

    <h4>Gruppe: @modelGroupedByGroup.ElementAt(i).Key.Name</h4>
    foreach (var proj in modelGroupedByGroup.ElementAt(i).GroupBy(o => o.Council))
    {
        if (proj.Key != null)
        {
            <h6>Fællesråd: @proj.Key.Name</h6>
        }

        var projects = modelGroupedByGroup.ElementAt(i).Where(o => o.Council == proj.Key);

        foreach (var pr in projects)
        {
            <div class="row">
                <div class="col-sm-12">
                    <dl class="dl-horizontal printing-border-ridge">
                        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
                        <dd>@Html.DisplayFor(model => pr.Id)</dd>

                        @{
                        if (pr.Description != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.Description)</dt>
                            <dd>@Html.DisplayFor(model => pr.Description)</dd>
                        }
                        }
                        @{
                        if (pr.AddressId != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.AddressId)</dt>
                            <dd class="aws-address-id" data-aws-id="@pr.AddressId">Henter adresse...</dd>
                        }
                        }
                            <dt>@Html.DisplayNameFor(model => model.CouncilPriority)</dt>
                            <dd>@Html.DisplayFor(model => pr.CouncilPriority)</dd>

                            <dt>@Html.DisplayNameFor(model => model.MunicipalityPriority)</dt>
                            <dd>@Html.DisplayFor(model => pr.MunicipalityPriority)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Budget)</dt>
                            <dd>@Html.DisplayFor(model => pr.Budget)</dd>
                        @{
                        if (pr.ConstructionProgram != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.ConstructionProgram)</dt>
                            <dd>@Html.DisplayFor(model => pr.ConstructionProgram)</dd>
                        }
                        }

                        @{
                        if (pr.LocalCommunity != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.LocalCommunity)</dt>
                            <dd>@Html.DisplayFor(model => pr.LocalCommunity)</dd>
                        }
                        }
                    </dl>
                </div>
            </div>
        }
    }

    if ((modelGroupedByGroup.ElementAt(i).Count() > 1 && i != Model.GroupBy(o => o.Group).Count() - 1)
        || (i == Model.GroupBy(o => o.Group).Count() - 1 &&  ungroupedProjects.Any()))
    {
        <hr class="printing-new-page" />
    }
}

    @{
        if (ungroupedProjects.Any())
        {
            <h4>Projekter uden gruppe</h4>
        }
    }

    @foreach (var proj in ungroupedProjects.GroupBy(o => o.Council))
    {
        if (proj.Key != null)
        {
             <h6>Fællesråd: @proj.Key.Name</h6>
        }
        var projects = ungroupedProjects.Where(o => o.Council == proj.Key);

        foreach (var pr in projects)
        {
        <div class="row">
            <div class="col-sm-12">
                <dl class="dl-horizontal printing-border-ridge">
                    <dt>@Html.DisplayNameFor(model => model.Id)</dt>
                    <dd>@Html.DisplayFor(model => pr.Id)</dd>

                    @{
                        if (pr.Description != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.Description)</dt>
                            <dd>@Html.DisplayFor(model => pr.Description)</dd>
                        }
                    }
                    @{
                        if (pr.AddressId != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.AddressId)</dt>
                            <dd class="aws-address-id" data-aws-id="@pr.AddressId">Henter adresse...</dd>
                        }
                    }
                    <dt>@Html.DisplayNameFor(model => model.CouncilPriority)</dt>
                    <dd>@Html.DisplayFor(model => pr.CouncilPriority)</dd>

                    <dt>@Html.DisplayNameFor(model => model.MunicipalityPriority)</dt>
                    <dd>@Html.DisplayFor(model => pr.MunicipalityPriority)</dd>

                    <dt>@Html.DisplayNameFor(model => model.Budget)</dt>
                    <dd>@Html.DisplayFor(model => pr.Budget)</dd>

                    @{
                        if (pr.ConstructionProgram != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.ConstructionProgram)</dt>
                            <dd>@Html.DisplayFor(model => pr.ConstructionProgram)</dd>
                        }
                    }

                    @{
                        if (pr.LocalCommunity != null)
                        {
                            <dt>@Html.DisplayNameFor(model => model.LocalCommunity)</dt>
                            <dd>@Html.DisplayFor(model => pr.LocalCommunity)</dd>
                        }
                    }
                </dl>
            </div>
        </div>
    }
}

@section Scripts{
    <script>
        function printPage() {
            window.print();
        }
    </script>
}